<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{185222de-2f69-4bea-a76f-3614533a9172}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	CounterFromUser1	: DINT;
	newvar	: DINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[CounterFromUser1	:= CounterFromUser1 +2;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>